### PR TITLE
Backend Development

### PR DESCRIPTION
**Pull request by fkadir**
Properties Endpoint Development

## What did we do?
- add pagination to all properties endpoint
- added unit testing for properties endpoint 

## Why did we do it?
pagination is needed for the browsing and tests are just good coding practice 

image
demo pagination in postman

### CODE REVIEW

**Comment by fkadir** [comment]
[Properties endpoint](https://trello.com/c/3uyYDGTZ/34-properties-endpoint)

**Comment by fkadir** [comment]
[Properties endpoint](https://trello.com/c/3uyYDGTZ/34-properties-endpoint)

**Comment by fkadir** [comment]
[Properties endpoint](https://trello.com/c/3uyYDGTZ/34-properties-endpoint)

**Comment by fkadir** [comment]
[Properties endpoint](https://trello.com/c/3uyYDGTZ/34-properties-endpoint)

**Comment by fkadir** [comment]
[Properties endpoint](https://trello.com/c/3uyYDGTZ/34-properties-endpoint)

**Review by CharlotteMartin1998 — APPROVED** [review]
Hurrah for testing and pagination. Looks great Fenna, well done.

**Pull request merged**
