### PR TITLE
Charlotte-components

### PR DESCRIPTION
**Pull request by CharlotteMartin1998**
# [INSERT TITLE OF PULL REQUEST HERE]

## What did we do?
Added in instruction if anyone wants to see what frontend looks like - located in Instructions.md in frontend folder.

Added draft carousel for fine tuning later on.

## Why did we do it?
Instructions are so that everyone can keep up to date with the look of the website - any questions or issues please let Oisin or I know.

The Carousel rough outline is for the property details page but will be worked on separately - It does not accept props yet, this is a very rough draft.

## Recording of New Feature in Action
n/a

## Accessibility Tests Run and Results
n/a

### CODE REVIEW

**Review by fkadir — APPROVED** [review]
LGTM thanks for making sure everybody can stay up to date with frontend dev!

**Review by oisintheginger — APPROVED** [review]
LGTM, great work on finding a good carousel library. It will suit our purposes brilliantly.

**Review by SeanLynch1 — APPROVED** [review]
Thanks for the explanation Charlotte. I now have a much clearer understanding of how Node.js and npm are used to initiate the web server. I wasn't previously aware of the process.

**Review by StephenAnokye94 — APPROVED** [review]

**Comment by nickykapur** [comment]
Looks good, great progress

**Pull request merged**
